//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPLE_STORE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int Id { get; set; }
        public Nullable<int> IdDonHang { get; set; }
        public decimal SoTien { get; set; }
        public string PhuongThuc { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public string TrangThai { get; set; }
        public string MaGiaoDich { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
